---

  - name: Install Postgres database packages
    apt: pkg={{ item }} state=installed update-cache=yes
    with_items:
    - postgresql
    - postgresql-server-dev-all
    become: true

  - name: Setup Postgres database
    postgresql_db: name={{ project_user }}
    become: true
    become_user: postgres

  - name: Postgres user access to database
    postgresql_user: db={{ project_user }} name={{ project_user }} priv=ALL
    become: true
    become_user: postgres
    notify: Restart postgres
